demo/browseApi.js, demo/getAccessToken.js, demo/getAllCategories.js, src/index.js, src/request.js
Implemented getAccessToken method and GetItem method.
Reference: https://developer.ebay.com/api-docs/static/oauth-tokens.html
=> Access token

.gitignore, demo/browseApi.js, src/buy-api.js, src/index.js, src/request.js
Implemented methods for the browse api call.
1. getItem.
2. getItemByLegacyId.
3. getItemsByItemGroup.
4. searchItems.
=> Browse Api call

src/buy-api.js
Fix Issue : https://github.com/ajay2507/ebay-node-api/issues/4
=> BUG FIX: fixed search items 

demo/taxonomyApi.js, src/index.js, src/request.js, src/taxonomy-api.js, src/utils.js
=> Taxonomy api Integration.

src/index.js
Removed unnecessary console.log calls, as they were getting in the way. No tests included, as the changes are not significant, and only extend to syntax improvements.
=> No need to output everything to console

.eslintrc, package.json, src/buildURL.js, src/index.js, src/request.js, src/taxonomy-api.js
Included eslint to format the checkstyle and included lint check.
=> included eslint and checkstlyle check

src/buildURL.js
Adding pageNumber for search of items.
=> Adding pagination to findItemsByKeywords

README.md, package.json, src/buildURL.js, src/buy-api.js, src/constants.js, src/index.js, src/merchandising.js, src/taxonomy-api.js, test/buildURL.test.js
Added support for ebay sandbox environment.
https://github.com/ajay2507/ebay-node-api/issues/25
=> Added support for sandbox environment.

src/request.js
Definition of an undefined variable
=> Fix for 'ReferenceError: dataString is not defined'

package.json, src/buy-api.js, src/utils.js, yarn.lock
Fix keyword space issue in search api.
https://github.com/pajaydev/ebay-node-api/issues/39
=> Fix keyword space in search api

src/buildURL.js
Hello,
I just add the possibility to put a sort order parameter and having access to seller informations.
Thanks !
=> Seller informations and sort order

src/buy-api.js, test/buildURL.test.js
buy.api.js now can offset the search queries
=> Update buy-api.js to accept offset query parameter

src/request.js
=> Remove this, causes unecessary undefined console logging

README.md, src/findingApi.js
**fidItemsByKeywords** accepts parameters now - keywords, pageNumber, limit, sortOrder. It still supports passing just one keyword.
Will highly appreciate if you update the npm package if all is good.
=> Finding api improvements

src/buy-api.js
just one line of code is added so everyone can put as an option in their call the aspect_filters parameter :)
=> added aspect_filters as a parameter at searchItem :)

src/findingApi.js
Possible types :  ISBN, UPC, EAN, or ReferenceID
Default : ReferenceID
=> Support to search with different type

demo/findingApi.js, package.json, src/common-utils/index.js, src/findingApi.js, src/merchandising.js, test/common.test.js, test/findingApi.test.js
https://github.com/pajaydev/ebay-node-api/issues/65
=> Support affiliate data in finding api

README.md, demo/findingApi.js, package.json, src/findingApi.js, src/index.js, test/findingApi.test.js
Added support to search items on eBay by category or keyword or both.
https://github.com/pajaydev/ebay-node-api/issues/67
=> Added findItemsAdvanced support

README.md
added important countryCode parameter which is necessary to search NON-US ebay sites
* [ X ] Documentation
=> add countryCode to README

src/common-utils/index.js
=> BUG FIX : made isString() available to  upperCase() scope
